name: app_fleet
description: A brilliant workspace manager & quick launcher specially designed for GNOME.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+5

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bitsdojo_window: ^0.1.5
  lottie: ^2.6.0
  file_picker: ^5.2.10
  flutter_svg: ^2.0.7
  flutter_animate: ^4.2.0+1
  url_launcher: ^6.1.14
  intl: ^0.18.1
  linux_plus: ^1.0.1
  connectivity_plus: ^4.0.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/picker/
    - assets/animations/
    - assets/scripts/
    - assets/themes/
  fonts:
    - family: Sen
      fonts:
        - asset: fonts/Sen.ttf
          weight: 400
        - asset: fonts/Sen-Bold.ttf
          weight: 700